### PR TITLE
python 3 update?

### PR DESCRIPTION
**Pull request by erantanen**
I made some possible updates to move the code to python 3. 
Not sure if you want to have two versions, one for 2.\* and one for 3.*

### CODE REVIEW

**Comment by cottonbeckfield** [comment]
I'll take a look at this sometime in the next few days. Thanks for taking the time to give it a sexy Python3 makeover.

**Comment by erantanen** [comment]
did you want to take this any further?

**Comment by cottonbeckfield** [comment]
Two things:

1) I'd like to leave the 2.7 version intact since a lot of people still use 2.7 on server-side systems (much to chagrin). However, it's still default on RHEL6 + Ubuntu14 which are widely used. Could you on your branch rename it to something like csrgen35.py ?  I could do it, but I think git tracks the contribution and would hate for yours not to show.

2) When I ran it in a virtualenv with python 3.5, the files that were created had random character insertions, namely the \n in both the output + files, which does not exist as an issue in 2.7. For example: 

`b'-----BEGIN CERTIFICATE REQUEST-----\nMIIC0TCCAbkCAQAwYzEWMBQGA1UEAwwNdGVzdC50ZXN0LmVkdTELMAkGA1UEBhMC\nVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExCzAJBgNVBAcMAlNGMQwwCgYDVQQKDANP\nUFMxDDAKBgNVBAsMA09QUzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB\nAORYqu1tOmqbotZLbAyV5p1lJqIIFmz1WNe5ncPZcnzM6mTucx8SqQXk279Jaqzi\njYiXF3iRwaGh4ABzj0I6ojwEZUlS9hZFboYvJ4zu3buZsdS4dLSN5SEu0z0G785J\nZTzzCLqMWV5LPj2Ky6COjwtomjWLM3QUF44wNN6nQ0+v7A0SdjaEjgCXVcTBA1h4\nMOP9xLzH5bmctBVvBIU0lG7+ZhuJ0tTHjEfciZmAQ7ZkzpcYCI03GQwbHBipVQQt\nLbf/12+x6OftWaABYCChbLrHCWdsBAfaBUqXugU7602Qn7Ht7FQACeb9gG/uGDnB\npp82nrhdCnLp6YPpOaISGakCAwEAAaApMCcGCSqGSIb3DQEJDjEaMBgwCwYDVR0P\nBAQDAgXgMAkGA1UdEwQCMAAwDQYJKoZIhvcNAQELBQADggEBABvywR2gR3XiQqtq\nU2TR7FotKByfr6+x0Qhu9fRLuEFdSBpfMA1HOCJJJIX0np3bN2klcgh+ANSenePp\noEioMq5a5uAD4RofyZDEK4EDC/hL7affh+z48BjgktlJF9tjcXR6bswEzeoa2bjS\nfGhCsyEQL+afMlhE4POwSk86rsrjmUrwR6ajGy7yJYCq+xz/au/XTIj6S2N+SqkI\nSQ8+kmjKlUhQ3YK1O9PvM9d5ROJ49VMJDVjscbJyQzf7pEeYyXVHTspcgOsmmvOh\nxeU4MR3/UPczXq7B/PuRWZ5akO8L4YvjfqsWpuW/a3wcp53aq3A5OxK8ZMp+0vsu\nohMntnw=\n-----END CERTIFICATE REQUEST-----\n'`

I'm assuming the b comes from:
`crypto.X509Extension(b"keyUsage",`
Which I'm not sure what the 'b' is for -- I'm assuming after a quick search it doesn't exist in 2.7 but relates to bytes literal in 3.x. (Ruby is my preferred scripting language, sorry). 
I'm assuming it's supposed to be
`crypto.X509Extension(b("keyUsage"), False, b("Digital Signature), Non Repudiation, Key Encipherment"),` based on the assumption of what it is.

As for the new lines... I'm assuming it's something to do with f.write(str( functionality (...) inserting those? It's throughout the csr/key as well as the end. 

Sorry it's taken me so long, I've just been busy so I hadn't had time to do a basic test yet and as of now no time to dig further. D: !!

**Comment by erantanen** [comment]
(tried your web page contact, no joy)

Here is a little write-up. 
https://docs.python.org/3/howto/pyporting.html
In Python 2 you could use the str type for both text and binary data. Unfortunately this confluence of two different concepts could lead to brittle code which sometimes worked for either kind of data, sometimes not. 

When I first started working with the x509Extensions in 3.\* had some strange errors that pointed to bite-array stuff, did some googling and found some further write-ups. 

csrgen.py back to 2.7 then made some mods to that.

**Pull request merged**
